version: "3.8"

services: 
  database: 
    image: mysql 
    environment: 
      MYSQL_ROOT_PASSWORD: admin 
      MYSQL_DATABASE: dockertest

    command: --default-authentication-plugin=mysql_native_password 
    ports: 
      - 4000:8080
    volumes: 
    - ./db_init:/docker-entrypoint-initdb.d 
    # mysql image will automatically run any .sql or .sh files in /docker-entrypoint-initdb.d

  backend: 
    build:
      context: ./ 
      dockerfile: Dockerfile.prod
    ports: 
      - 3000:8080
    environment: 
      DB_URL: root:admin@tcp(database)/dockertest 
    
    restart: unless-stopped 

    
    command: sh geolocation/docker-entrypoint.prod.sh

  # backend-test: 
  #   image: geolocation-service-assignment_backend
  #   command: go test 

# Run this by "docker-compose -f docker-compose.prod.yml up"
# "docker-compose -f docker-compose.prod.yml up -d" for detached mode. 